all:
	make -C debug
	make -C sram
	make -C fifo
	make -C useq
	make -C bsram
	make -C uart
	make -C timer

clean:
	make -C debug clean
	make -C sram clean
	make -C fifo clean
	make -C useq clean
	make -C bsram clean
	make -C uart clean
	make -C timer clean

