all:
	make -C math
	make -C vga
	make -C ib16
	make -C yod_pla
	make -C debug
	make -C sram
	make -C fifo
	make -C useq
	make -C uart
	make -C timer

clean:
	make -C math clean
	make -C vga clean
	make -C ib16 clean
	make -C yod_pla clean
	make -C debug clean
	make -C sram clean
	make -C fifo clean
	make -C useq clean
	make -C uart clean
	make -C timer clean

