`ifndef NANOFPU_OP
`define NANOFPU_OP

`define NANOFPU_OP_FADD  4'd0
`define NANOFPU_OP_FSUB  4'd1
`define NANOFPU_OP_FMUL  4'd2
`define NANOFPU_OP_FDIV  4'd3
`define NANOFPU_OP_FLDI  4'd4
`define NANOFPU_OP_FSTI  4'd5
`define NANOFPU_OP_FSQRT 4'd6
`define NANOFPU_OP_FCMP  4'd7
`define NANOFPU_OP_IADD  4'd8
`define NANOFPU_OP_NOP   4'd15

`define NANOFPU_FL_FADD  (16'd1 << `NANOFPU_OP_FADD)
`define NANOFPU_FL_FSUB  (16'd1 << `NANOFPU_OP_FSUB)
`define NANOFPU_FL_FMUL  (16'd1 << `NANOFPU_OP_FMUL)
`define NANOFPU_FL_FDIV  (16'd1 << `NANOFPU_OP_FDIV)
`define NANOFPU_FL_FLDI  (16'd1 << `NANOFPU_OP_FLDI)
`define NANOFPU_FL_FSTI  (16'd1 << `NANOFPU_OP_FSTI)
`define NANOFPU_FL_FSQRT (16'd1 << `NANOFPU_OP_FSQRT)
`define NANOFPU_FL_FCMP  (16'd1 << `NANOFPU_OP_FCMP)
`define NANOFPU_FL_IADD  (16'd1 << `NANOFPU_OP_IADD)

`define NANOFPU_FL_NOP   (16'd1 << `NANOFPU_OP_NOP)

// bitmask to say which are enabled, since fadd and fsub are the same you just
// need NANOFPU_FL_FADD to enable both
`define NANOFPU_FUNCS_ALL     (`NANOFPU_FL_FADD | `NANOFPU_FL_FSUB | `NANOFPU_FL_FMUL | `NANOFPU_FL_FDIV | `NANOFPU_FL_FLDI | `NANOFPU_FL_FSTI | `NANOFPU_FL_FSQRT | `NANOFPU_FL_FCMP | `NANOFPU_FL_IADD)
`define NANOFPU_FUNCS_MULADD  (`NANOFPU_FL_FADD | `NANOFPU_FL_FSUB | `NANOFPU_FL_FMUL)

`endif
